name: book_app
description: "A Flutter app for browsing, booking, and managing various services with ease."

# Not publishing to pub.dev
publish_to: 'KreativDev'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Core UI & Design
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  auto_size_text: ^3.0.0
  dotted_border: ^3.1.0
  font_awesome_flutter: ^10.9.0
  flutter_staggered_animations: ^1.1.1

  # Charts & Sliders
  fl_chart: ^1.0.0
  syncfusion_flutter_charts: ^30.1.42
  syncfusion_flutter_core: ^30.1.42
  syncfusion_flutter_sliders: ^30.1.42
  carousel_slider: ^5.1.1
  table_calendar: ^3.2.0

  # Localization & Internationalization
  flutter_localization: ^0.3.3
  intl: ^0.20.2

  # State Management
  get: ^4.7.2

  # Editors
  flutter_quill: ^11.4.2

  # File & Image Picker
  file_picker: ^10.2.1
  image_picker: ^1.1.2
  # google_fonts: ^6.3.0

  # Utilities
  # logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # lint: ^2.8.0 # Optional advanced linting
  # device_preview: ^1.3.1 # For testing on multiple screen sizes

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter_18pt-Regular.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Medium.ttf
        - asset: assets/fonts/Inter/Inter_18pt-SemiBold.ttf
        - asset: assets/fonts/Inter/Inter_18pt-Bold.ttf
        - asset: assets/fonts/Inter/Inter_24pt-SemiBold.ttf
